/**
 * Bakes the ecosystem's `.env.example` files into the docs site.
 *
 * The browser tool has no network access by design, so the examples it offers
 * have to ship with the bundle. Reading them at request time would also mean
 * the sibling repositories had to exist on the deployed container, and they do
 * not.
 *
 * Safe to inline: an `.env.example` is the schema, not the environment. A key
 * with a value in it here is a placeholder someone wrote to show the shape.
 * Run this after adding or renaming a variable in any repository, and commit
 * the result.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';

const REPOS_DIR = resolve(import.meta.dirname, '../..');
const OUT = resolve(import.meta.dirname, '../site/lib/env-presets.ts');

const PRESETS: Array<{ id: string; label: string; repo: string }> = [
  { id: 'genesis', label: 'Genesis (full stack app)', repo: 'genesis' },
  { id: 'ui-pro', label: 'olwibaUI Pro (docs + auth)', repo: 'olwibaUI-Pro' },
  { id: 'ui', label: 'olwibaUI', repo: 'olwibaUI' },
  { id: 'cn', label: 'olwibaCN', repo: 'olwibaCN' },
  { id: 'docs', label: 'olwibaDOCS', repo: 'olwibaDOCS' },
  { id: 'sync', label: 'olwibaSYNC', repo: 'olwibaSYNC' },
];

const found: Array<{ id: string; label: string; example: string }> = [];
const missing: string[] = [];

for (const preset of PRESETS) {
  const path = resolve(REPOS_DIR, preset.repo, '.env.example');
  if (!existsSync(path)) {
    missing.push(preset.repo);
    continue;
  }

  const example = await readFile(path, 'utf8');
  if (example.trim() === '') {
    missing.push(`${preset.repo} (empty)`);
    continue;
  }

  found.push({ id: preset.id, label: preset.label, example });
}

// A missing sibling means the preset silently disappears from the site, which
// is the shape of bug this repository exists to catch. Say so.
if (missing.length > 0) {
  console.warn(`[env-presets] skipped, no .env.example: ${missing.join(', ')}`);
}

const body = `// @generated by scripts/generate-env-presets.ts — do not edit.
// Regenerate with: bun run presets:generate

export interface EnvPreset {
  id: string
  label: string
  example: string
}

export const envPresets: EnvPreset[] = ${JSON.stringify(found, null, 2)}
`;

await writeFile(OUT, body, 'utf8');
console.log(`[env-presets] wrote ${found.length} preset(s) to site/lib/env-presets.ts`);
